name: Feature request
description: Suggest a change to StoryPress
title: "Feature: "
body:
  - type: textarea
    id: problem
    attributes:
      label: What problem should this solve?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: What would you like StoryPress to do?
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives you considered
